import type { Metadata } from "next";
import { Rubik, Rubik_Beastly } from "next/font/google";
import "./globals.css";
import ReduxStoreProvider from "./ReduxStoreProvider";
import Header from "@/components/ClientSideComponent/HeaderComponent/Header";
import Copyright from "@/components/ServerSideComponent/CopyrightComponent/Copyright";
import Footer from "@/components/ServerSideComponent/FooterComponent/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add desired font weights
});

export const metadata: Metadata = {
  title: "Med'Z",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <head></head>
      <body className="antialiased">
        <ReduxStoreProvider>
          <Header />
          {children}
          <Footer />
          <Copyright />
        </ReduxStoreProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
