import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import ReduxStoreProvider from "./ReduxStoreProvider";
import Header from "@/components/ClientSideComponent/HeaderComponent/Header";
import Copyright from "@/components/ServerSideComponent/CopyrightComponent/Copyright";
import Footer from "@/components/ServerSideComponent/FooterComponent/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const montserrat = Merriweather({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Add desired font weights
});

export const metadata: Metadata = {
  title: "Med'Z",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body className="antialiased">
        <ReduxStoreProvider>
          <Header />
          {children}
          <Footer />
          <Copyright />
        </ReduxStoreProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
